version: "3.8"

networks:
  localstack-net:
    name: localstack-net
    driver: bridge

services:
  localstack:
    container_name: lambda-test-dotnet
    image: localstack/localstack
    environment:
      - DEBUG=1   
      - DATA_DIR=/var/lib/localstack/data
      - LAMBDA_EXECUTOR=docker-reuse
      - LAMBDA_REMOTE_DOCKER=false
      - LAMBDA_REMOVE_CONTAINERS=true
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}   
      - SERVICES=lambda,events, s3, sqs, sns
      - AWS_DEFAULT_REGION=us-east-1
      - HOST_URL=http://localhost:4566
      - AWS_ACCESS_KEY_ID=guest
      - AWS_SECRET_ACCESS_KEY=guest
      - AWS_DEFAULT_OUTPUT=json
    ports:
      - 4566:4566
      - 4571:4571     
    volumes:
      - ./data:/var/lib/localstack      
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./setup:/docker-entrypoint-initaws.d
